[pytest]
markers = 
    basic: Very simple functional tests, no error or significant logic testing.
    checkpointing: Function to test that the graph is saved/loaded correctly.
    valid: Make sure the test case is valid (no testing of actual functionality).
    matching: Use the test data to check the graph node matching.
    aggregate: Use the provided test data to test all aggregation options.
    deaggregate: Use the provided test data to test all deaggregate options.
pythonpath = . src tests
