[pytest]
markers = 
    basic: Very simple functional tests, no error or significant logic testing.
    checkpointing: Function to test that the graph is saved/loaded correctly.
pythonpath = . src tests
